# -*- coding: utf-8 -*-
"""Copy of youtubevideotranscript.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A43HCd3Xcl6mT1ktWLvxHQ7MECYwnW-O
"""

# refer to https://pypi.org/project/youtube-transcript-api/
# install a library
!pip install youtube-transcript-api

# import libraries
from youtube_transcript_api import YouTubeTranscriptApi
import pandas as pd

# instantiate a TranscriptList object 
#transcript_list = YouTubeTranscriptApi.list_transcripts('BR_dUDf8g9k')
transcript_list = YouTubeTranscriptApi.list_transcripts('aICPlOIH77Q')
transcript_list

# fetch the english transcript
transcript = transcript_list.find_transcript(['en'])
transcript_fetched = transcript.fetch()
transcript_fetched

# get english texts
transcript_text = [item['text'] for item in transcript_fetched]
transcript_text